language: java
jdk: openjdk12

before_install:
- ./ci/install_ssh_key.sh
install:
  - ./ci/install_packages.sh
script:
  - ./gradlew test jgivenTestReport
deploy:
  skip_cleanup: true
  provider: script
  script: ./ci/deploy_doc.sh
  on:
    branch: master