language: java
install: true
jdk: openjdk12
script:
- "./gradlew test jgivenTestReport"
before_install:
- openssl aes-256-cbc -K $encrypted_716a67714777_key -iv $encrypted_716a67714777_iv -in key.enc -out key -d
- chmod 600 github_deploy_key
- eval $(ssh-agent -s)
- ssh-add github_deploy_key
