language: java
jdk: openjdk12

install:
  - ./ci/install_packages.sh
script:
  - ./gradlew test jgivenTestReport
before_deploy:
  - ./ci/setup_ssh_key.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./ci/deploy_docs.sh
  on:
    branch: master