language: java
install: true
jdk: openjdk12
install:
  - npm install -g --silent gh-pages
script:
  - "./gradlew test jgivenTestReport"
  - "git config user.email \"ci@agiledojo.de"
  - "git config user.name \"CI\""
  - "gh-pages --dist build/reports/jgiven/test/html"
before_install:
- openssl aes-256-cbc -K $encrypted_716a67714777_key -iv $encrypted_716a67714777_iv -in key.enc -out key -d
- chmod 600 key
- eval $(ssh-agent -s)
- ssh-add key
- sudo apt-get update
- sudo apt-get npm
